############################################
## global settings & macros
############################################     

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
stages:
  - build
  - test
  - doc

.latex: &latex
  stage: doc
  image: blang/latex:ubuntu

.atlas: &atlas
  image: atlas/analysisbase:21.2.64
  before_script:
    - source /home/atlas/release_setup.sh

.standalone: &standalone    
  image: rootproject/root-ubuntu16  

.ctest: &ctest  
  stage: test
  script:
    - cd build
    - ctest

.cmake: &cmake    
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
      - build

.GNUmake: &GNUmake    
  stage: build
  script:
    make -j1
  artifacts:
    paths:
      - libRooUnfold.so
      - RooUnfoldDict_rdict.pcm
      - libRooUnfold.rootmap

.GNUtest: &GNUtest          
  stage: test
  script:
    - python examples/RooUnfoldExample.py

.dAgostini: &dAgostini
  <<: *standalone
  before_script:
    - sudo apt-get update
    - sudo apt-get install wget
    - export FC=gfortran
    - bash get_dagos_bayes.sh
    
############################################
## building
############################################     
    
compile_atlas:
  <<: *atlas
  <<: *cmake

compile_cmake:
  <<: *standalone
  <<: *cmake

compile_GNUmake:
  <<: *standalone
  <<: *GNUmake  

compile_cmake_dAgostini:
  <<: *dAgostini
  <<: *cmake
  
compile_GNUmake_dAgostini:
  <<: *dAgostini
  <<: *GNUmake  


############################################           
## testing      
############################################

test_atlas:
  <<: *atlas
  <<: *ctest  
  dependencies:
    - compile_atlas    

test_cmake:
  <<: *standalone
  <<: *ctest  
  dependencies:
    - compile_cmake

test_GNUmake:
  <<: *standalone
  <<: *GNUtest
  dependencies:
    - compile_GNUmake

############################################         
## documentation
############################################

doc_bayes_errors:
  <<: *latex
  script:
    - cd doc/bayes_errors
    - pdflatex bayes_errors.tex
  artifacts:
    paths:
      - doc/bayes_errors/bayes_errors.pdf
    
doc_phystat2011:
  <<: *latex
  script:
    - cd doc/phystat2011
    - pdflatex phystat2011_adye.tex
  artifacts:
    paths:
      - doc/phystat2011/phystat2011_adye.pdf

doc_unfolding2011:      
  <<: *latex
  script:
    - cd doc/unfolding2010
    - pdflatex adye_tim.tex
  artifacts:
    paths:
      - doc/unfolding2010/adye_tim.pdf

